import { Event, Training, Competition, Post, TeamMember, CoreValue } from './types';

export const siteConfig = {
  name: 'ZCTech Community',
  tagline: 'Pusat Ekosistem Cybersecurity & Tech Talent Indonesia',
  description:
    'Wadah terbuka bagi para antusias keamanan siber, pentester, dan pengembang teknologi Indonesia. Berbagi wawasan, ikuti pelatihan rutin, dan tingkatkan keahlian teknis Anda.',
  url: 'https://community.zctech.id',
  discordInvite: 'https://discord.gg/s67RfATTBk',
  email: 'community@zctech.id',
  socials: {
    discord: 'https://discord.gg/s67RfATTBk',
    instagram: 'https://instagram.com/zctech.id',
    twitter: 'https://x.com/zctech_id',
    linkedin: 'https://linkedin.com/company/zctech',
    github: 'https://github.com/zctech-community',
  },
  stats: {
    members: 1250,
    eventsCompleted: 48,
    trainingDelivered: 24,
    competitions: 15,
  },
};

export const coreValues: CoreValue[] = [
  {
    title: 'Open Knowledge',
    description: 'Pengetahuan seputar cybersecurity dan teknologi harus terbuka dan dapat diakses siapa saja.',
  },
  {
    title: 'Hands-on Learning',
    description: 'Belajar paling efektif lewat praktik langsung di lab, CTF, dan proyek nyata.',
  },
  {
    title: 'Collaborative Growth',
    description: 'Tumbuh bersama melalui diskusi, mentoring, dan kolaborasi antar anggota komunitas.',
  },
  {
    title: 'Ethical Impact',
    description: 'Menerapkan keahlian secara bertanggung jawab dan memberi dampak positif bagi industri.',
  },
];

export const team: TeamMember[] = [
  { name: 'William Kornelius', role: 'Founder & Community Lead', image: '/kegiatan/img-07.jpg', socmed: [{ platform: 'linkedin', url: 'https://linkedin.com/in/williamkornelius' }] },
  { name: 'Ari Setiawan', role: 'Lead Pentest Mentor', image: '/kegiatan/img-08.jpg', socmed: [{ platform: 'github', url: 'https://github.com' }] },
  { name: 'Dewi Lestari', role: 'Training Program Manager', image: '/kegiatan/img-09.jpg', socmed: [{ platform: 'linkedin', url: 'https://linkedin.com' }] },
  { name: 'Rizki Fauzi', role: 'CTF & Competition Lead', image: '/kegiatan/img-10.jpg', socmed: [{ platform: 'github', url: 'https://github.com' }] },
];

export const events: Event[] = [
  {
    id: '1',
    slug: 'workshop-bug-bounty-101',
    title: 'Workshop Bug Bounty 101',
    description: 'Belajar dasar-dasar bug bounty, platform, dan teknik reconnaissance untuk pemula.',
    content: 'Workshop ini dirancang untuk pemula yang ingin memulai karir bug bounty. Kita akan membahas platform seperti HackerOne, Bugcrowd, dan Intigriti, lalu praktik reconnaissance dan identifikasi low-hanging fruit.',
    coverImage: '/kegiatan/img-01.jpg',
    eventDate: '2026-08-15T09:00:00+07:00',
    endDate: '2026-08-15T12:00:00+07:00',
    location: 'Samarinda — Online via Discord',
    type: 'workshop',
    status: 'upcoming',
    regLink: 'https://discord.gg/s67RfATTBk',
  },
  {
    id: '2',
    slug: 'tech-meetup-agustus',
    title: 'Tech Meetup Agustus: Zero Trust Architecture',
    description: 'Diskusi interaktif tentang konsep Zero Trust dan implementasinya di startup Indonesia.',
    content: 'Zero Trust bukan lagi pilihan, melainkan kebutuhan. Meetup ini akan membahas arsitektur, tools, dan case study implementasi Zero Trust pada infrastruktur cloud.',
    coverImage: '/kegiatan/img-02.jpg',
    eventDate: '2026-08-22T19:00:00+07:00',
    location: 'Samarinda — Hybrid & Discord',
    type: 'meetup',
    status: 'upcoming',
  },
  {
    id: '3',
    slug: 'ctf-beginner-bootcamp',
    title: 'CTF Beginner Bootcamp',
    description: 'Bootcamp CTF 3 hari untuk pemula yang ingin memahami kategori web, forensics, dan crypto.',
    content: 'Bootcamp intensif selama 3 hari dengan mentor berpengalaman. Setiap hari mencakup teori singkat, hands-on challenge, dan review.',
    coverImage: '/kegiatan/img-03.jpg',
    eventDate: '2026-09-05T08:00:00+07:00',
    endDate: '2026-09-07T17:00:00+07:00',
    location: 'Online',
    type: 'competition',
    status: 'upcoming',
    regLink: 'https://discord.gg/s67RfATTBk',
  },
  {
    id: '4',
    slug: 'hands-on-pentest-lab',
    title: 'Hands-on Pentest Lab',
    description: 'Praktik penetration testing terhadap intentionally vulnerable VM.',
    content: 'Lab ini mengajarkan metodologi pentest dari reconnaissance hingga reporting. Peserta akan mendapatkan target VM untuk dieksplorasi.',
    coverImage: '/kegiatan/img-04.jpg',
    eventDate: '2026-05-10T13:00:00+07:00',
    location: 'Samarinda — Online',
    type: 'workshop',
    status: 'completed',
  },
  {
    id: '5',
    slug: 'webinar-malware-analysis',
    title: 'Webinar Malware Analysis',
    description: 'Pengenalan statik dan dinamik malware analysis dengan tools open source.',
    content: 'Webinar ini membahas alur kerja malware analyst, tools (YARA, Cuckoo, REMnux), dan demo analisis sample ringan.',
    coverImage: '/kegiatan/img-05.jpg',
    eventDate: '2026-06-20T19:30:00+07:00',
    location: 'Samarinda — Online via Discord',
    type: 'webinar',
    status: 'completed',
  },
  {
    id: '6',
    slug: 'community-gathering-q2',
    title: 'Community Gathering Q2 2026',
    description: 'Kumpul bersama anggota ZCTech untuk berbagi cerita dan networking.',
    content: 'Gathering tahunan komunitas ZCTech untuk saling berkenalan, berbagi cerita, dan merencanakan kegiatan Q3.',
    coverImage: '/kegiatan/img-06.jpg',
    eventDate: '2026-07-05T15:00:00+07:00',
    location: 'Samarinda',
    type: 'meetup',
    status: 'completed',
  },
];

export const trainingPrograms: Training[] = [
  {
    id: 't1',
    slug: 'cybersecurity-fundamentals',
    title: 'Cybersecurity Fundamentals',
    description: 'Pelatihan dasar keamanan siber untuk pemula yang ingin memahami konsep dan terminologi.',
    syllabus: ['Network & OS Fundamentals', 'Common Vulnerabilities (OWASP Top 10)', 'Intro to Linux for Security', 'Security Tools Crash Course', 'Incident Response Basics'],
    category: 'cybersecurity',
    level: 'beginner',
    duration: '8 jam (2 sesi)',
    format: 'online',
    prerequisites: 'Tidak diperlukan pengalaman khusus.',
    trainer: 'Ari Setiawan',
    price: 'Gratis',
    isActive: true,
    coverImage: '/kegiatan/img-01.jpg',
  },
  {
    id: 't2',
    slug: 'web-pentest-bootcamp',
    title: 'Web Pentest Bootcamp',
    description: 'Bootcamp intensif untuk menguasai teknik penetration testing aplikasi web modern.',
    syllabus: ['Recon & Mapping', 'Authentication & Session Attacks', 'Injection (SQLi, XSS, SSTI)', 'Business Logic Bugs', 'Reporting & Remediation'],
    category: 'cybersecurity',
    level: 'intermediate',
    duration: '24 jam (6 sesi)',
    format: 'online',
    prerequisites: 'Memahami dasar HTTP, HTML, dan JavaScript.',
    trainer: 'William Kornelius',
    price: 'Rp 1.500.000',
    isActive: true,
    coverImage: '/kegiatan/img-02.jpg',
  },
  {
    id: 't3',
    slug: 'network-security-masterclass',
    title: 'Network Security Masterclass',
    description: 'Mendalami keamanan jaringan, traffic analysis, dan defense strategy.',
    syllabus: ['TCP/IP & Protocol Analysis', 'Sniffing & Spoofing', 'Firewall & IDS/IPS', 'VPN & Secure Remote Access', 'Network Forensics'],
    category: 'networking',
    level: 'intermediate',
    duration: '16 jam (4 sesi)',
    format: 'hybrid',
    prerequisites: 'Dasar jaringan dan OSI layer.',
    trainer: 'Rizki Fauzi',
    price: 'Rp 1.200.000',
    isActive: true,
    coverImage: '/kegiatan/img-03.jpg',
  },
  {
    id: 't4',
    slug: 'python-for-security-automation',
    title: 'Python for Security Automation',
    description: 'Belajar otomasi keamanan siber menggunakan Python untuk efisiensi kerja.',
    syllabus: ['Python Basics for Security', 'Parsing Logs & IOCs', 'Building Recon Scripts', 'API Integration for Threat Intel', 'Automated Report Generation'],
    category: 'programming',
    level: 'beginner',
    duration: '12 jam (3 sesi)',
    format: 'online',
    prerequisites: 'Dasar pemrograman.',
    trainer: 'Dewi Lestari',
    price: 'Rp 800.000',
    isActive: true,
    coverImage: '/kegiatan/img-04.jpg',
  },
];

export const competitions: Competition[] = [
  {
    id: 'c1',
    slug: 'cyber-hackathon-2026',
    title: 'Cyber Hackathon 2026',
    organizer: 'Kementerian Komunikasi dan Informatika',
    description: 'Kompetisi inovasi keamanan siber nasional dengan fokus solusi untuk pemerintahan digital.',
    category: 'hackathon',
    deadline: '2026-09-01T00:00:00+07:00',
    prizeInfo: 'Total hadiah Rp 500 juta',
    externalLink: 'https://example.com/cyber-hackathon',
    coverImage: '/kegiatan/img-11.jpg',
  },
  {
    id: 'c2',
    slug: 'national-ctf-qualifier',
    title: 'National CTF Qualifier',
    organizer: 'Indonesia Cyber Security Forum',
    description: 'Babak kualifikasi CTF nasional untuk mewakili Indonesia di ajang internasional.',
    category: 'CTF',
    deadline: '2026-08-30T23:59:00+07:00',
    prizeInfo: 'Ticket ke Regional Finals',
    externalLink: 'https://example.com/national-ctf',
    coverImage: '/kegiatan/img-03.jpg',
  },
  {
    id: 'c3',
    slug: 'blockchain-security-bounty',
    title: 'Blockchain Security Bounty',
    organizer: 'DeFi Protocol X',
    description: 'Bug bounty untuk smart contract DeFi dengan reward hingga $25,000.',
    category: 'bug bounty',
    deadline: '2026-10-15T00:00:00+07:00',
    prizeInfo: 'Hingga $25,000',
    externalLink: 'https://example.com/defi-bounty',
    coverImage: '/kegiatan/img-02.jpg',
  },
  {
    id: 'c4',
    slug: 'ui-ux-security-challenge',
    title: 'UX Secure Design Challenge',
    organizer: 'Tech Design Indonesia',
    description: 'Desain aplikasi yang aman dan user-friendly berdasarkan skenario risiko.',
    category: 'UI/UX',
    deadline: '2026-08-25T00:00:00+07:00',
    prizeInfo: 'Portfolio showcase + mentor session',
    externalLink: 'https://example.com/ux-secure',
    coverImage: '/kegiatan/img-04.jpg',
  },
];

export const posts: Post[] = [
  {
    id: 'p1',
    slug: 'memulai-karir-bug-bounty',
    title: 'Memulai Karir Bug Bounty untuk Pemula',
    excerpt: 'Panduan praktis memulai bug bounty dari nol: mindset, platform, dan langkah pertama.',
    content: 'Bug bounty adalah cara belajar sekaligus mendapatkan penghasilan. Artikel ini membahas cara memilih platform, membaca policy, dan menemukan bug pertama.',
    coverImage: '/kegiatan/img-04.jpg',
    category: 'tutorial',
    tags: ['bug bounty', 'career', 'hacking'],
    author: 'Ari Setiawan',
    publishedAt: '2026-07-20T08:00:00+07:00',
    readingTime: 6,
  },
  {
    id: 'p2',
    slug: 'mengenal-owasp-top-10-2025',
    title: 'Mengenal OWASP Top 10 2025',
    excerpt: 'Ringkasan risiko keamanan aplikasi web terbaru dan cara mitigasi utamanya.',
    content: 'OWASP Top 10 terus berkembang mengikuti lanskap ancaman. Kita bahas satu per satu kategori terbaru beserta contoh kasus nyata.',
    coverImage: '/kegiatan/img-05.jpg',
    category: 'tutorial',
    tags: ['owasp', 'web security', 'pentest'],
    author: 'William Kornelius',
    publishedAt: '2026-07-15T08:00:00+07:00',
    readingTime: 8,
  },
  {
    id: 'p3',
    slug: 'writeup-ctf-pwn-heat',
    title: 'Writeup CTF: Pwn The Heat',
    excerpt: 'Writeup lengkap challenge pwnable dari kompetisi lokal dengan eksploitasi buffer overflow.',
    content: 'Challenge ini mengajarkan buffer overflow di stack modern dengan mitigasi partial. Simak langkah analisis sampai dapat flag.',
    coverImage: '/kegiatan/img-03.jpg',
    category: 'writeup',
    tags: ['ctf', 'pwn', 'binary exploitation'],
    author: 'Rizki Fauzi',
    publishedAt: '2026-07-10T08:00:00+07:00',
    readingTime: 12,
  },
  {
    id: 'p4',
    slug: 'cybersecurity-di-indonesia-2026',
    title: 'Tren Cybersecurity di Indonesia 2026',
    excerpt: 'Laporan singkat tren ancaman, talenta, dan regulasi keamanan siber di Indonesia.',
    content: 'Indonesia menghadapi ancaman siber yang kompleks seiring transformasi digital. Artikel ini mengulas tren utama dan peluang talenta.',
    coverImage: '/kegiatan/img-06.jpg',
    category: 'news',
    tags: ['indonesia', 'trends', 'policy'],
    author: 'Dewi Lestari',
    publishedAt: '2026-07-05T08:00:00+07:00',
    readingTime: 5,
  },
  {
    id: 'p5',
    slug: 'opinion-ethical-hacker',
    title: 'Etika Seorang Ethical Hacker',
    excerpt: 'Refleksi tentang tanggung jawab dan etika di dunia offensive security.',
    content: 'Kekuatan teknis harus diimbangi etika. Artikel ini membahas prinsip responsible disclosure, privasi, dan profesionalisme.',
    coverImage: '/kegiatan/img-11.jpg',
    category: 'opinion',
    tags: ['ethics', 'hacking', 'responsible disclosure'],
    author: 'William Kornelius',
    publishedAt: '2026-06-28T08:00:00+07:00',
    readingTime: 7,
  },
];

export const nearestEvent = events
  .filter((e) => new Date(e.eventDate) > new Date())
  .sort((a, b) => new Date(a.eventDate).getTime() - new Date(b.eventDate).getTime())[0];
